services:
  db:
    image: postgres:17
    container_name: bitza-2026-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ${HOME}/databases/bitza-2026-v17:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}