# Generated by Django 5.1.4 on 2025-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractform',
            name='html_file',
            field=models.CharField(max_length=50, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='status',
            field=models.CharField(choices=[('A', 'Активный'), ('B', 'Устаревший')], max_length=50, verbose_name='Статус'),
        ),
    ]
