# Generated by Django 5.1.4 on 2025-01-25 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_contact_gender_alter_building_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='rent.contract', verbose_name='Договор')),
                ('form', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rent.contractform', verbose_name='Бланк договора')),
            ],
        ),
    ]
