# Generated by Django 5.1.4 on 2025-02-08 18:05

import django.db.models.deletion
import rent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_contractprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='form',
            field=models.ForeignKey(blank=True, default=rent.models.get_latest_contract_form, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rent.contractform', verbose_name='Бланк договора'),
        ),
        migrations.AlterField(
            model_name='contractprint',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='contractprint',
            name='form',
            field=models.ForeignKey(blank=True, default=rent.models.get_latest_contract_form, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rent.contractform', verbose_name='Бланк договора'),
        ),
    ]
