# Generated by Django 5.2.17 on 2026-08-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_alter_contractprint_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='document_name',
            field=models.CharField(blank=True, choices=[('Паспорт РФ', 'Паспорт РФ'), ('Паспорт другого государства', 'Паспорт другого государства'), ('Удостоверение', 'Удостоверение'), ('Военный билет', 'Военный билет'), ('Паспорт Таджикистана', 'Паспорт Таджикистана'), ('Паспорт Узбекистана', 'Паспорт Узбекистана')], default='Паспорт РФ', max_length=30, null=True, verbose_name='Документ'),
        ),
    ]
