# Generated by Django 5.2.17 on 2026-08-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_alter_contact_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type_cold_water_counter',
            field=models.CharField(choices=[('N', 'Нет'), ('M', 'Ручной'), ('A', 'Автоматический')], default='N', max_length=1, verbose_name='Счётчик холодной воды'),
        ),
        migrations.AddField(
            model_name='room',
            name='type_hot_water_counter',
            field=models.CharField(choices=[('N', 'Нет'), ('M', 'Ручной'), ('A', 'Автоматический')], default='N', max_length=1, verbose_name='Счётчик горячей воды'),
        ),
        migrations.AddField(
            model_name='room',
            name='type_watt_counter',
            field=models.CharField(choices=[('N', 'Нет'), ('M', 'Ручной'), ('A', 'Автоматический')], default='N', max_length=1, verbose_name='Электросчётчик'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_watt_counter',
            field=models.BooleanField(default=False, help_text='Устарело, оставлено для обратной совместимости — используйте type_watt_counter. Можно будет удалить после месяца работы нового приложения в проде.', verbose_name='Есть электросчётчик'),
        ),
    ]
