# Generated by Django 5.2.17 on 2026-08-28 21:20

from django.db import migrations

# Комнаты 2го дома, где уже стоят автоматические Zigbee-счётчики (импорт из bitza_ha),
# плюс Д.00 ("Сруб" в bitza_ha — один счётчик на весь Рубленый дом, привязан к этой комнате).
AUTOMATIC_WATT_ROOMS = [
    '1.06', '1.07', '1.08', '1.09', '1.10',
    '2.06', '2.07', '2.08', '2.09', '2.10',
    'Д.00',
]


def forwards(apps, schema_editor):
    Room = apps.get_model('rent', 'Room')
    Room.objects.filter(has_watt_counter=True).update(type_watt_counter='M')
    Room.objects.filter(shortname__in=AUTOMATIC_WATT_ROOMS).update(
        type_watt_counter='A',
        has_watt_counter=True,
    )


def backwards(apps, schema_editor):
    Room = apps.get_model('rent', 'Room')
    Room.objects.all().update(
        type_watt_counter='N',
        type_hot_water_counter='N',
        type_cold_water_counter='N',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_room_type_cold_water_counter_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
