# Generated by Django 5.2.17 on 2026-08-29 09:24

import rent.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_backfill_counter_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image_file',
            field=models.ImageField(storage=rent.storage_backends.DocumentStorage(), upload_to='documents', verbose_name='Изображение'),
        ),
    ]
