# Generated by Django 5.2.17 on 2026-08-29 09:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('gas_taken_date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, default=27, null=True)),
                ('room', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('receiver', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('sender_user_id', models.IntegerField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True)),
                ('linked_record', models.ForeignKey(blank=True, db_column='linked_record_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gas.gasrecord')),
            ],
        ),
    ]
