# Generated by Django 5.0.3 on 2024-04-23 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0002_room_has_watt_counter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('kwt_count', models.IntegerField(verbose_name='КВт')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Обновлён')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='rent.room', verbose_name='Комната')),
                ('user', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
