# Generated by Django 5.0.3 on 2024-05-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='kwt_count',
            field=models.DecimalField(decimal_places=1, help_text='КВт', max_digits=10, verbose_name='КВт'),
        ),
    ]
